name: Update Profile Info
on:
  schedule:
    - cron: "0 */12 * * *" 
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update-all:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      # 1. Setup inicial
      - uses: actions/checkout@v3

      # 2. Gerar Gr√°fico Pacman
      - name: Generate Pacman Graph
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: lcrochaDEV

      # 3. Organizar arquivos para a branch 'output'
      - name: Organize files
        run: |
          mkdir -p dist
          cp pacman-contribution-graph.svg dist/pacman-contribution-graph.svg
          cp pacman-contribution-graph.svg dist/pacman-contribution-graph-dark.svg
