on:
  schedule:
    - cron: "0 */12 * * *" 
  workflow_dispatch: # Permite rodar manualmente
  push:
    branches:
    - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: generate pacman-contribution-graph.svg
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: lcrochaDEV

      - name: Organize files
        run: |
          mkdir -p dist
          # A action gera um arquivo chamado github-contribution-grid-snake.svg
          cp github-contribution-grid-snake.svg dist/pacman-contribution-graph.svg
          cp github-contribution-grid-snake.svg dist/pacman-contribution-graph-dark.svg

      - name: push to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
