name: Generate pacman animation

on:
  schedule:
    - cron: "0 */12 * * *" 
  workflow_dispatch: # Permite rodar manualmente
  push:
    branches:
    - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: generate pacman-contribution-graph.svg
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: lcrochaDEV

      - name: Organize files
        run: |
          mkdir -p dist
          # Procura o arquivo gerado e move para a pasta dist
          find . -name "pacman-contribution-graph.svg" -exec cp {} dist/pacman-contribution-graph.svg \;
          find . -name "pacman-contribution-graph.svg" -exec cp {} dist/pacman-contribution-graph-dark.svg \;
          
          # Verifica se o arquivo foi realmente copiado para evitar erro no pr√≥ximo passo
          ls -R dist/

      - name: push to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
