name: Update Badges
on:
  schedule:
    - cron: "0 2 * * *" # Atualiza todo dia Ã s 02h
  workflow_dispatch: # Permite rodar manualmente

jobs:
  update-badges:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: pemtajo/badge-readme@main
        with:
          CREDLY_USER: lucas-rocha.e2b61fbf
          NUMBER_LAST_BADGES: 12
