name: Update Badges
on:
  schedule:
    - cron: "0 2 * * *" # Roda diariamente às 02:00 UTC
  workflow_dispatch:   # Permite rodar manualmente para testar agora

jobs:
  update-badges:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Obrigatório para a Action fazer commit no seu README
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Update Badges from Credly
        uses: pemtajo/badge-readme@main
        with:
          CREDLY_USER: lucas-rocha.e2b61fbf
          NUMBER_LAST_BADGES: 12
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
